import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CustomCursor from "@/components/common/CustomCursor";
import Navbar from "@/components/shared/Navbar";
import { Toaster } from "sonner";
import Footer from "@/components/shared/Footer";
import { domain_url } from "@/constants/api";
import TierCityServices from "@/components/shared/TierCityLinks";
import FloatingCTA from "@/components/common/FloatingCTA";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* website schema */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "WebSite",
              name: "Quantumtech Digital",
              alternateName: "Quantumtech",
              url: `${domain_url}/`,
              potentialAction: {
                "@type": "SearchAction",
                target: `${domain_url}/?q={search_term_string}`,
                "query-input": "required name=search_term_string",
              },
            }),
          }}
        />

        {/* global business */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              "@id": `${domain_url}/#organization`,
              name: "Quantumtech Digital",
              url: `${domain_url}/`,
              logo: `${domain_url}/logo.png`,
              description:
                "Quantumtech Digital is a leading IT services and website development company in India, providing web development, SEO, and digital marketing solutions across all Indian cities.",
              foundingDate: "2024",
              founder: {
                "@type": "Person",
                name: "Aryan Raj",
                sameAs: ["https://www.linkedin.com/in/aryan-raj-raushan/"],
              },
              areaServed: {
                "@type": "Country",
                name: "India",
              },
              sameAs: [
                "https://www.linkedin.com/company/quantumtech-digital",
                "https://www.facebook.com/quantumtechdigital",
                "https://www.instagram.com/quantumtech_digital/",
              ],
            }),
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <CustomCursor />
        <div className='bg-black w-full'>
          {children}
        </div>
        <Toaster position="top-right" richColors />
        <TierCityServices />
        <Footer />
        <FloatingCTA />
      </body>
    </html>
  );
}
