import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CustomCursor from "@/components/common/CustomCursor";
import Navbar from "@/components/shared/Navbar";
import { Toaster } from "sonner";
import Footer from "@/components/shared/Footer";
import { domain_url } from "@/constants/api";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* website schema */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "WebSite",
              name: "Quantumtech Digital",
              alternateName: "Quantumtech",
              url: `${domain_url}/`,
              potentialAction: {
                "@type": "SearchAction",
                target: `${domain_url}/search?q={search_term_string}`,
                "query-input": "required name=search_term_string",
              },
            }),
          }}
        />

        {/* organisation */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              name: "Quantumtech Digital",
              url: `${domain_url}`,
              description:
                "Quantumtech Digital is a website development and digital marketing agency helping businesses grow online across India.",
              founder: {
                "@type": "Person",
                name: "Aryan Raj",
                sameAs: ["https://www.linkedin.com/in/aryan-raj-raushan/"],
              },
              sameAs: ["https://www.linkedin.com/in/aryan-raj-raushan/"],
            }),
          }}
        />

        {/* Local Business Schema */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "LocalBusiness",
              name: "Quantumtech Digital",
              address: {
                "@type": "PostalAddress",
                addressLocality: "Biharsharif",
                addressRegion: "Bihar",
                postalCode: "803101",
                addressCountry: "IN",
              },
              areaServed: [
                {
                  "@type": "City",
                  name: "Biharsharif",
                },
                {
                  "@type": "AdministrativeArea",
                  name: "Nalanda",
                },
                {
                  "@type": "City",
                  name: "Patna",
                },
                {
                  "@type": "City",
                  name: "Gurugram",
                },
                {
                  "@type": "AdministrativeArea",
                  name: "Delhi NCR",
                },
                {
                  "@type": "State",
                  name: "Bihar",
                },
                {
                  "@type": "State",
                  name: "West Bengal",
                },
                {
                  "@type": "State",
                  name: "Uttar Pradesh",
                },
                {
                  "@type": "Country",
                  name: "India",
                },
              ],

              url: `${domain_url}`,
              priceRange: "₹4999+",
              founder: {
                "@type": "Person",
                name: "Aryan Raj",
                sameAs: ["https://www.linkedin.com/in/aryan-raj-raushan/"],
              },
            }),
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <CustomCursor />
        {children}
        <Toaster position="top-right" richColors />
        <Footer />
      </body>
    </html>
  );
}
